#pragma once

#define VIAL_KEYBOARD_UID {0x3E, 0x1D, 0x08, 0x5F, 0xCC, 0x02, 0xB6, 0x53}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 11 }

#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define DYNAMIC_KEYMAP_LAYER_COUNT 4
