#pragma once

#define VIAL_KEYBOARD_UID {0xDB, 0x06, 0x15, 0xB1, 0x4E, 0x43, 0x78, 0xCE}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 2 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 13 }

#define VIAL_TAP_DANCE_ENTRIES 4
#define VIAL_COMBO_ENTRIES 4
#define DYNAMIC_KEYMAP_LAYER_COUNT 4