#pragma once

#define VIAL_KEYBOARD_UID {0xBD, 0xE5, 0x6D, 0xB2, 0x8C, 0xE0, 0x6C, 0x4E}

#define VIAL_UNLOCK_COMBO_ROWS { 2 }
#define VIAL_UNLOCK_COMBO_COLS { 2 }

#define VIAL_ENCODER_DEFAULT { KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS }